name: Copy Files to Lightsail

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Copy files to Lightsail server
        run: |
          # Install SSH client
          sudo apt-get update
          sudo apt-get install -y putty-tools
      - name: Copy files to Lightsail server
        run: |
          # copy file to lightsail
          # Replace the placeholders with actual values
          WINDOWS_SERVER_IP="3.110.130.37"
          WINDOWS_SERVER_USER="Administrator"
          WINDOWS_SERVER_PASSWORD="akqR3XeigseYHlWxD$T8ZtpWu&T*BkJm"
          DESTINATION_FOLDER="C:\test3"
          # Use pscp to copy files to Windows server using username and password
          echo y | pscp -pw "$WINDOWS_SERVER_PASSWORD" -r "${{ github.workspace }}/*" "$WINDOWS_SERVER_USER@$WINDOWS_SERVER_IP:$DESTINATION_FOLDER"
           
