name: Copy Files to Lightsail

on:
 workflow_dispatch: 
 
jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Copy files to Lightsail server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.RDP_USERNAME }}
          password: ${{ secrets.RDP_PASSWORD }}
          port: 22  # Adjust the port if needed
          script: |
            # Create a directory on the server (adjust the path as needed)
            mkdir "C:\test2"

            # Copy files from the repository to the server
            scp -o StrictHostKeyChecking=no -r $GITHUB_WORKSPACE/lightsail ${username}@${host}:"C:\test2"
