name: Copy Files to Lightsail

on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Copy files to Lightsail server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.RDP_USERNAME }}
          password: ${{ secrets.RDP_PASSWORD }}
          port: 22  # Adjust the port if needed
          script: |
            # Create a directory on the server (adjust the path as needed)
            Invoke-Command -ScriptBlock {
              New-Item -ItemType Directory -Path "C:\test2" -Force
            }

            # Copy files from the repository to the server
            $sourcePath = "$env:GITHUB_WORKSPACE\lightsail"
            $destinationPath = "C:\test2"
            Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse
